import { imagesForType } from "./images";

// DEMO PROPERTY DATA — fictional listings for sales-demo purposes only.
// agentIndex references AGENTS_SEED array index (0-3).

export interface PropertySeed {
  address: string;
  city: string;
  state: string;
  zip: string;
  neighborhood: string;
  price: number;
  listingType: "For Sale" | "For Rent";
  propertyType: string;
  bedrooms: number;
  bathrooms: string;
  sqft: number;
  lotSize: string;
  description: string;
  features: string[];
  availability: string;
  showingAvailability: string;
  agentIndex: number;
}

const raw: (Omit<PropertySeed, "features"> & { features: string[] })[] = [
  { address: "1120 Aurora St", city: "Houston", state: "TX", zip: "77004", neighborhood: "Midtown", price: 315000, listingType: "For Sale", propertyType: "Condo", bedrooms: 2, bathrooms: "2.0", sqft: 1150, lotSize: "N/A", description: "Bright corner-unit condo walking distance to Midtown restaurants and light rail, with an open living area and private balcony.", features: ["Balcony", "In-unit laundry", "Covered parking", "Gym access"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 1 },
  { address: "2214 Studewood St", city: "Houston", state: "TX", zip: "77008", neighborhood: "Montrose", price: 459000, listingType: "For Sale", propertyType: "Townhouse", bedrooms: 3, bathrooms: "2.5", sqft: 1900, lotSize: "0.06 acres", description: "Modern three-story townhouse near Montrose with rooftop deck, high ceilings, and an updated kitchen.", features: ["Rooftop deck", "Hardwood floors", "Stainless appliances", "2-car garage"], availability: "Active", showingAvailability: "Weekdays after 3pm, weekends flexible", agentIndex: 2 },
  { address: "845 Heights Blvd", city: "Houston", state: "TX", zip: "77007", neighborhood: "The Heights", price: 525000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 3, bathrooms: "2.0", sqft: 2100, lotSize: "0.14 acres", description: "Charming updated bungalow on tree-lined Heights Blvd with a wraparound porch and renovated kitchen.", features: ["Wraparound porch", "Renovated kitchen", "Original hardwoods", "Fenced yard"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "1500 McKinney St, Unit 812", city: "Houston", state: "TX", zip: "77010", neighborhood: "Downtown", price: 1850, listingType: "For Rent", propertyType: "Apartment", bedrooms: 1, bathrooms: "1.0", sqft: 720, lotSize: "N/A", description: "High-rise downtown apartment with skyline views, on-site gym, and rooftop pool.", features: ["Skyline view", "Rooftop pool", "Fitness center", "Pet friendly"], availability: "Active", showingAvailability: "Daily 9am–7pm", agentIndex: 1 },
  { address: "3300 Main St, Unit 204", city: "Houston", state: "TX", zip: "77002", neighborhood: "Midtown", price: 2150, listingType: "For Rent", propertyType: "Apartment", bedrooms: 2, bathrooms: "2.0", sqft: 980, lotSize: "N/A", description: "Spacious two-bedroom apartment near Midtown's restaurant row with a modern kitchen and in-unit washer/dryer.", features: ["In-unit laundry", "Walk-in closets", "Covered parking", "Pet friendly"], availability: "Active", showingAvailability: "Daily 9am–7pm", agentIndex: 1 },
  { address: "14022 Memorial Dr", city: "Houston", state: "TX", zip: "77079", neighborhood: "Energy Corridor", price: 389000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "2.5", sqft: 2400, lotSize: "0.19 acres", description: "Well-maintained family home near the Energy Corridor with an open floor plan and large backyard.", features: ["Open floor plan", "Large backyard", "Granite counters", "3-car garage"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "5522 Cinco Ranch Blvd", city: "Katy", state: "TX", zip: "77450", neighborhood: "Cinco Ranch", price: 415000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.0", sqft: 2650, lotSize: "0.20 acres", description: "Two-story Cinco Ranch home with community amenities nearby, an island kitchen, and a covered patio.", features: ["Island kitchen", "Covered patio", "Community pool access", "Zoned Katy ISD"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "26110 Cross Creek Bend Ln", city: "Katy", state: "TX", zip: "77494", neighborhood: "Cross Creek Ranch", price: 479900, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.0", sqft: 2900, lotSize: "0.22 acres", description: "Newer construction in Cross Creek Ranch with a chef's kitchen, game room, and extended covered patio.", features: ["Chef's kitchen", "Game room", "Extended patio", "Energy efficient"], availability: "Active", showingAvailability: "Weekdays after 2pm, weekends flexible", agentIndex: 0 },
  { address: "23503 Grand Lakes Xing", city: "Katy", state: "TX", zip: "77494", neighborhood: "Grand Lakes", price: 329000, listingType: "For Sale", propertyType: "Townhouse", bedrooms: 3, bathrooms: "2.5", sqft: 1850, lotSize: "0.08 acres", description: "Low-maintenance Grand Lakes townhome close to shopping and top-rated schools.", features: ["Low maintenance", "Attached garage", "Community lake access"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 2 },
  { address: "4110 Kingsland Blvd, Unit 3", city: "Katy", state: "TX", zip: "77450", neighborhood: "Cinco Ranch", price: 2400, listingType: "For Rent", propertyType: "Rental", bedrooms: 3, bathrooms: "2.0", sqft: 1950, lotSize: "0.12 acres", description: "Spacious rental home in Cinco Ranch with a private backyard and two-car garage, zoned to Katy ISD.", features: ["Private backyard", "2-car garage", "Zoned Katy ISD", "Pet friendly"], availability: "Active", showingAvailability: "Weekdays after 4pm, weekends flexible", agentIndex: 1 },
  { address: "2402 Commercial Park Dr", city: "Sugar Land", state: "TX", zip: "77479", neighborhood: "Telfair", price: 549000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.5", sqft: 3100, lotSize: "0.24 acres", description: "Executive home in Telfair with a study, media room, and resort-style community amenities.", features: ["Home office", "Media room", "Community amenities", "3-car garage"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 2 },
  { address: "3811 University Blvd, Unit 5B", city: "Sugar Land", state: "TX", zip: "77479", neighborhood: "First Colony", price: 265000, listingType: "For Sale", propertyType: "Condo", bedrooms: 2, bathrooms: "2.0", sqft: 1100, lotSize: "N/A", description: "Well-kept First Colony condo close to shopping, dining, and major commuter routes.", features: ["Covered parking", "Community pool", "Updated flooring"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 1 },
  { address: "1 Riverstone Estate Dr", city: "Sugar Land", state: "TX", zip: "77479", neighborhood: "Riverstone", price: 875000, listingType: "For Sale", propertyType: "Luxury Home", bedrooms: 5, bathrooms: "4.5", sqft: 4200, lotSize: "0.35 acres", description: "Custom Riverstone estate with a pool, outdoor kitchen, and premium finishes throughout.", features: ["Pool", "Outdoor kitchen", "Custom finishes", "3-car garage"], availability: "Active", showingAvailability: "By appointment only", agentIndex: 3 },
  { address: "6119 New Territory Blvd", city: "Sugar Land", state: "TX", zip: "77479", neighborhood: "New Territory", price: 2600, listingType: "For Rent", propertyType: "Townhouse", bedrooms: 3, bathrooms: "2.5", sqft: 2000, lotSize: "0.07 acres", description: "Modern New Territory townhome for lease with an attached garage and community lake trails.", features: ["Attached garage", "Community trails", "Recent updates"], availability: "Active", showingAvailability: "Weekdays after 3pm, weekends flexible", agentIndex: 1 },
  { address: "18 Grogans Mill Rd", city: "The Woodlands", state: "TX", zip: "77380", neighborhood: "Creekside Park", price: 625000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.0", sqft: 3300, lotSize: "0.28 acres", description: "Creekside Park home backing to a greenbelt, with a gourmet kitchen and oversized primary suite.", features: ["Greenbelt lot", "Gourmet kitchen", "Oversized primary suite", "3-car garage"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 3 },
  { address: "42 Sterling Ridge Pl", city: "The Woodlands", state: "TX", zip: "77381", neighborhood: "Sterling Ridge", price: 1150000, listingType: "For Sale", propertyType: "Luxury Home", bedrooms: 5, bathrooms: "5.0", sqft: 4800, lotSize: "0.40 acres", description: "Sterling Ridge luxury estate with a private pool, home theater, and wooded views.", features: ["Private pool", "Home theater", "Wooded lot", "Wine room"], availability: "Active", showingAvailability: "By appointment only", agentIndex: 3 },
  { address: "9 Grogans Mill Ct, Unit 12", city: "The Woodlands", state: "TX", zip: "77380", neighborhood: "Grogans Mill", price: 1950, listingType: "For Rent", propertyType: "Condo", bedrooms: 2, bathrooms: "2.0", sqft: 1050, lotSize: "N/A", description: "Quiet Grogans Mill condo near The Woodlands Waterway with a private patio.", features: ["Private patio", "Covered parking", "Walk to Waterway"], availability: "Active", showingAvailability: "Weekdays after 4pm, weekends flexible", agentIndex: 1 },
  { address: "13210 Bridgeland Creek Pkwy", city: "Cypress", state: "TX", zip: "77433", neighborhood: "Bridgeland", price: 399000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "2.5", sqft: 2550, lotSize: "0.18 acres", description: "Bridgeland home with trail access, a bright open-concept layout, and a covered patio.", features: ["Trail access", "Open concept", "Covered patio", "2-car garage"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "10722 Fairfield Place Dr", city: "Cypress", state: "TX", zip: "77433", neighborhood: "Fairfield", price: 355000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 3, bathrooms: "2.0", sqft: 2150, lotSize: "0.16 acres", description: "Move-in-ready Fairfield home with updated flooring and a spacious fenced backyard.", features: ["Updated flooring", "Fenced backyard", "Community pool"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "17503 Towne Lake Pkwy", city: "Cypress", state: "TX", zip: "77433", neighborhood: "Towne Lake", price: 299000, listingType: "For Sale", propertyType: "Townhouse", bedrooms: 3, bathrooms: "2.5", sqft: 1750, lotSize: "0.06 acres", description: "Towne Lake townhome near the boardwalk with a low-maintenance yard and attached garage.", features: ["Near boardwalk", "Attached garage", "Low maintenance"], availability: "Active", showingAvailability: "Weekdays after 3pm, weekends flexible", agentIndex: 2 },
  { address: "22315 Klein Church Rd", city: "Spring", state: "TX", zip: "77389", neighborhood: "Klein", price: 329900, listingType: "For Sale", propertyType: "Single Family", bedrooms: 3, bathrooms: "2.0", sqft: 1980, lotSize: "0.17 acres", description: "Comfortable Klein-area home with an updated kitchen and large covered back patio.", features: ["Updated kitchen", "Covered patio", "Storage shed"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 0 },
  { address: "6811 Augusta Pines Dr", city: "Spring", state: "TX", zip: "77389", neighborhood: "Augusta Pines", price: 469000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.0", sqft: 2800, lotSize: "0.21 acres", description: "Augusta Pines golf-course-area home with a two-story living room and gourmet kitchen.", features: ["Two-story living room", "Gourmet kitchen", "3-car garage"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 3 },
  { address: "3402 Spring Trails Blvd", city: "Spring", state: "TX", zip: "77373", neighborhood: "Spring Trails", price: 2050, listingType: "For Rent", propertyType: "Rental", bedrooms: 3, bathrooms: "2.0", sqft: 1850, lotSize: "0.15 acres", description: "Spring Trails rental home with a fenced yard and community trail access, close to I-45.", features: ["Fenced yard", "Trail access", "Pet friendly"], availability: "Active", showingAvailability: "Weekdays after 4pm, weekends flexible", agentIndex: 1 },
  { address: "3005 Shadow Creek Pkwy", city: "Pearland", state: "TX", zip: "77584", neighborhood: "Shadow Creek Ranch", price: 389900, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "2.5", sqft: 2500, lotSize: "0.18 acres", description: "Shadow Creek Ranch home near lakes and trails with an open kitchen and covered patio.", features: ["Open kitchen", "Covered patio", "Community lakes"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 2 },
  { address: "2901 Silverlake Village Dr", city: "Pearland", state: "TX", zip: "77584", neighborhood: "Silverlake", price: 429000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 4, bathrooms: "3.0", sqft: 2700, lotSize: "0.20 acres", description: "Silverlake home with a versatile flex room, large kitchen island, and extended patio.", features: ["Flex room", "Kitchen island", "Extended patio"], availability: "Active", showingAvailability: "Weekdays 10am–6pm, weekends by appointment", agentIndex: 2 },
  { address: "3611 Southdown Rd, Unit 2", city: "Pearland", state: "TX", zip: "77581", neighborhood: "Southdown", price: 1750, listingType: "For Rent", propertyType: "Apartment", bedrooms: 2, bathrooms: "1.5", sqft: 900, lotSize: "N/A", description: "Affordable Pearland apartment close to shopping, with a private patio and reserved parking.", features: ["Private patio", "Reserved parking", "Pet friendly"], availability: "Active", showingAvailability: "Daily 9am–7pm", agentIndex: 1 },
  { address: "1901 Rice Blvd", city: "Houston", state: "TX", zip: "77007", neighborhood: "Rice Military", price: 985000, listingType: "For Sale", propertyType: "Luxury Home", bedrooms: 4, bathrooms: "4.5", sqft: 3600, lotSize: "0.12 acres", description: "Contemporary Rice Military build with rooftop terrace, downtown views, and designer finishes.", features: ["Rooftop terrace", "Downtown views", "Designer finishes", "Elevator ready"], availability: "Active", showingAvailability: "By appointment only", agentIndex: 3 },
  { address: "6410 Bellfort Ave", city: "Houston", state: "TX", zip: "77081", neighborhood: "Sharpstown", price: 265000, listingType: "For Sale", propertyType: "Single Family", bedrooms: 3, bathrooms: "2.0", sqft: 1650, lotSize: "0.15 acres", description: "Affordable Sharpstown starter home with a recently updated roof and fenced backyard.", features: ["Updated roof", "Fenced backyard", "Close to major highways"], availability: "Pending", showingAvailability: "Currently under contract — inquire for similar listings", agentIndex: 0 },
];

export const PROPERTIES_SEED: PropertySeed[] = raw.map((p, idx) => ({ ...p }));

export function seedImages(propertyType: string, idx: number) {
  return imagesForType(propertyType, idx);
}
